Adding font-end distributables into nginx container

diff --git a/nginx/Dockerfile b/nginx/Dockerfile
--- a/nginx/Dockerfile
+++ b/nginx/Dockerfile
@@ -1,12 +1,20 @@
-FROM nginx:latest
+FROM alpine:3
 
 LABEL maintainer="GhwFluffy <ghw@ghwfluffy.com>"
 LABEL description="PayPwn Ingress"
 
 ENV LANG="en_US.utf8"
+ENV LC_ALL="en_US.utf8"
 ENV LANGUAGE="en_US:en"
 
 ENV PS1="nginx>\\w$ "
+
+# Install nginx
+RUN set -eux; \
+    apk add --no-cache \
+        nginx \
+        ; \
+    true
 
 # Save mime types and remove all other configuration
 RUN set -eux; \
@@ -33,3 +41,43 @@ RUN set -eux; \
 RUN set -eux; \
     rm -rf /usr/share/nginx; \
     true
+
+# Get paypwn front-end/build files
+COPY ./paybuddy/vue /var/paypwn/paybuddy/vue
+COPY ./paybuddy/api /var/paypwn/paybuddy/api
+COPY ./setup /setup
+
+# Protobuf build dependencies
+RUN set -eux; \
+    apk add --no-cache \
+        build-base \
+        npm \
+        protobuf-dev \
+        ; \
+    true
+
+# Build front-end
+ENV NPM_CONFIG_TMP="npm"
+ENV NPM_CONFIG_CACHE="npm"
+ENV NPM_CONFIG_PREFIX="npm"
+RUN set -eux; \
+    cd /var/paypwn/paybuddy; /setup/setup-vite; \
+    mv vue/dist www; \
+    true
+
+# Cleanup
+RUN set -eux; \
+    apk del --no-cache \
+        build-base \
+        npm \
+        protobuf-dev \
+        ; \
+    rm -rf \
+        /setup \
+        /var/paypwn/paybuddy/api \
+        /var/paypwn/paybuddy/vue \
+        ; \
+    true
+
+COPY ./nginx/bin/entrypoint /entrypoint
+ENTRYPOINT ["/entrypoint"]
